# https://taskfile.dev

version: "3"
dotenv: [".env", ".env.example", "{{.HOME}}/.env"]

vars:
  TASK_REMOTE: "github.com/lwmacct/251207-task-remote.git/"

includes:
  env:
    taskfile: https://{{.TASK_REMOTE}}/.task/env.yml?ref=main
    optional: true
    flatten: true

  git:
    taskfile: https://{{.TASK_REMOTE}}/.task/git.yml?ref=main
    optional: true

  ci:
    taskfile: .task/ci.yml
    optional: true

tasks:
  image:check:
    desc: 检查 Dockerfile 语法
    cmds:
      - docker buildx build --check -f containers/ubuntu-noble-desktop-v1.17.0/Dockerfile .
