name: ubuntu-noble-desktop-v1.19.0

on:
  push:
    branches:
      - main
    paths:
      - "containers/ubuntu-noble-desktop-v1.19.0/**"
      - "!containers/ubuntu-noble-desktop-v1.19.0/README.md"
      - ".github/workflows/ubuntu-noble-desktop-v1.19.0.yml"
      - ".github/workflows/publish-image.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-ubuntu-noble-desktop-v1.19.0
  cancel-in-progress: true

jobs:
  publish:
    uses: ./.github/workflows/publish-image.yml
    with:
      image_channel: ubuntu-noble-desktop-v1.19.0
      dockerfile: containers/ubuntu-noble-desktop-v1.19.0/Dockerfile
